export const allProductDetails = [
  {
    prod_name: 'Smartwatch',
    prod_id: 's01',
    prod_img: '../../assets/project img/banner img/watch.webp',
    prod_sub: [
      {
        comp_id: 'ss01',
        comp_name: 'Samsung',
        comp_model: 'SAMSUNG GALAXY Watch 5',
        comp_price: 35999,
        comp_prodDetails1: 'Model Name                      Galaxy Watch 5 ',
        comp_prodDetails2: 'Display Size                    1.36inch',
        comp_prodDetails3: 'Display Resolution              450 x 450pixels',
        comp_prodDetails4: 'Call Function                   Yes',
        comp_prodDetails5: 'Bluetoth Version                5.2',
        comp_prodDetails6: 'Voice Control                   yes',
        comp_prodDetails7: 'Operating System                Wear Os',
        comp_prodDetails8: 'Charge Type                     Wireless charger',
        comp_prodDetails9: 'Battery Life                    Upto 4o Hours',
        comp_prodDetails10: 'Warranty Summary                1 Year',

        comp_img: '../../assets/project img/smart watch/samsung watch 5.jpg',
        comp_imgdetails1:
          '../../assets/project img/smart watch/samsung watch 5.jpg',
        comp_imgdetails2: '../../assets/project img/smart watch/sam2.webp',
        comp_imgdetails3: '../../assets/project img/smart watch/sam3.webp',

        comp_imgdetails: '../../assets/project img/watchdetails2/sam1.png',

        comp_link:'http://localhost:4200/contact',
        
      },

      {
        comp_id: 'ss02',
        comp_name: 'Samsung',
        comp_model: 'SAMSUNG GALAXY Watch 4 LTE',
        comp_price: 30999,
        comp_prodDetails1: 'Model Name                      Galaxy Watch 5 LTE',
        comp_prodDetails2: 'Display Size                    1.36inch',
        comp_prodDetails3: 'Display Resolution              450 x 450pixels',
        comp_prodDetails4: 'Call Function                   Yes',
        comp_prodDetails5: 'Bluetoth Version                5.2',
        comp_prodDetails6: 'Voice Control                   yes',
        comp_prodDetails7: 'Operating System                Wear Os',
        comp_prodDetails8: 'Charge Type                     Wireless charger',
        comp_prodDetails9: 'Battery Life                    Upto 4o Hours',
        comp_prodDetails10: 'Warranty Summary                1 Year',

        comp_img: '../../assets/project img/smart watch/sam2.webp',
        comp_imgdetails1:
          '../../assets/project img/smart watch/samsung watch 5.jpg',
        comp_imgdetails2: '../../assets/project img/smart watch/sam2.webp',
        comp_imgdetails3: '../../assets/project img/smart watch/sam3.webp',

        comp_imgdetails: '../../assets/project img/watchdetails2/sam1.png',

        comp_link:
          'https://www.flipkart.com/samsung-watch-5-44mmsuper-amoled-displaylte-calling-body-composition-tracking/p/itmc9c74c7f4f22b?pid=SMWGH7W45SAFCCV4&lid=LSTSMWGH7W45SAFCCV46KCNIF&marketplace=FLIPKART&q=samsung+watch+5&store=ajy&srno=s_1_1&otracker=AS_Query_OrganicAutoSuggest_4_11_na_na_ps&otracker1=AS_Query_OrganicAutoSuggest_4_11_na_na_ps&fm=organic&iid=60c92518-9944-4ada-8c4e-7621232e9472.SMWGH7W45SAFCCV4.SEARCH&ppt=hp&ppn=homepage&ssid=wxhy5pxu740000001669951341793&qH=5da8e54149127e84',
      },

      {
        comp_id: 'ss03',
        comp_name: 'Samsung',
        comp_model: 'APPLE Watch Series 3',
        comp_price: 20990,
        comp_prodDetails1: 'Model Name                      Watch Series 3  ',
        comp_prodDetails2: 'Display Size                    1.4inch',
        comp_prodDetails3: 'Display Resolution              272 x 340pixels',
        comp_prodDetails4: 'Call Function                   No',
        comp_prodDetails5: 'Bluetoth Version                4.2',
        comp_prodDetails6: 'Voice Control                   No',
        comp_prodDetails7: 'Operating System                WatchOs 4',
        comp_prodDetails8: 'Charge Type                     Wireless charger',
        comp_prodDetails9: 'Battery Life                    Upto 20 Hours',
        comp_prodDetails10: 'Warranty Summary                1 Year',

        comp_img: '../../assets/project img/smart watch/a3.webp',
        comp_imgdetails1: '../../assets/project img/smart watch/a2.webp',
        comp_imgdetails2: '../../assets/project img/smart watch/a1.webp',
        comp_imgdetails3: '../../assets/project img/smart watch/a2.webp',

        comp_imgdetails: '../../assets/project img/watchdetails2/sam1.png',

        comp_link:
          'https://www.flipkart.com/samsung-watch-5-44mmsuper-amoled-displaylte-calling-body-composition-tracking/p/itmc9c74c7f4f22b?pid=SMWGH7W45SAFCCV4&lid=LSTSMWGH7W45SAFCCV46KCNIF&marketplace=FLIPKART&q=samsung+watch+5&store=ajy&srno=s_1_1&otracker=AS_Query_OrganicAutoSuggest_4_11_na_na_ps&otracker1=AS_Query_OrganicAutoSuggest_4_11_na_na_ps&fm=organic&iid=60c92518-9944-4ada-8c4e-7621232e9472.SMWGH7W45SAFCCV4.SEARCH&ppt=hp&ppn=homepage&ssid=wxhy5pxu740000001669951341793&qH=5da8e54149127e84',
      },
      {
        comp_id: 'ss04',
        comp_name: 'Samsung',
        comp_model: 'SAMSUNG GALAXY Watch 4 ',
        comp_price: 11650,
        comp_prodDetails1: 'Model Name                      SAMSUNG Watch 4  ',
        comp_prodDetails2: 'Display Size                    1.4inch',
        comp_prodDetails3: 'Display Resolution              450 x 450pixels',
        comp_prodDetails4: 'Call Function                   Yes',
        comp_prodDetails5: 'Bluetoth Version                4.2',
        comp_prodDetails6: 'Voice Control                   Yes',
        comp_prodDetails7: 'Operating System                Wear0s',
        comp_prodDetails8: 'Charge Type                     Wireless charger',
        comp_prodDetails9: 'Battery Life                    Upto 40 Hours',
        comp_prodDetails10: 'Warranty Summary                1 Year',

        comp_img: '../../assets/project img/smart watch/s1.webp',
        comp_imgdetails1: '../../assets/project img/smart watch/s1.webp',
        comp_imgdetails2: '../../assets/project img/smart watch/s2.webp',
        comp_imgdetails3: '../../assets/project img/smart watch/s3.webp',

        comp_imgdetails: '../../assets/project img/watchdetails2/sam1.png',

        comp_link:
          'https://www.flipkart.com/samsung-watch-5-44mmsuper-amoled-displaylte-calling-body-composition-tracking/p/itmc9c74c7f4f22b?pid=SMWGH7W45SAFCCV4&lid=LSTSMWGH7W45SAFCCV46KCNIF&marketplace=FLIPKART&q=samsung+watch+5&store=ajy&srno=s_1_1&otracker=AS_Query_OrganicAutoSuggest_4_11_na_na_ps&otracker1=AS_Query_OrganicAutoSuggest_4_11_na_na_ps&fm=organic&iid=60c92518-9944-4ada-8c4e-7621232e9472.SMWGH7W45SAFCCV4.SEARCH&ppt=hp&ppn=homepage&ssid=wxhy5pxu740000001669951341793&qH=5da8e54149127e84',
      },
      {
        comp_id: 'ss05',
        comp_name: 'fasttrack',
        comp_model: 'Fastrack Reflex Play+ ',
        comp_price: 6995,
        comp_prodDetails1:
          'Model Name                      Fastrack Reflex Play+  ',
        comp_prodDetails2: 'Display Size                    1.4inch',
        comp_prodDetails3: 'Display Resolution              360 x 360pixels',
        comp_prodDetails4: 'Call Function                   Yes',
        comp_prodDetails5: 'Bluetoth Version                5.0',
        comp_prodDetails6: 'Voice Control                   Yes',
        comp_prodDetails7: 'Operating System                N/A',
        comp_prodDetails8: 'Charge Type                     Wireless charger',
        comp_prodDetails9: 'Battery Life                    Upto 7 Days',
        comp_prodDetails10: 'Warranty Summary                1 Year',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_img: '../../assets/project img/smart watch/f1.webp',
        comp_imgdetails1: '../../assets/project img/smart watch/f1.webp',
        comp_imgdetails2: '../../assets/project img/smart watch/f2.webp',
        comp_imgdetails3: '../../assets/project img/smart watch/f3.webp',
        comp_imgdetails: '../../assets/project img/watchdetails2/fast.png',
        comp_link:
          'https://www.flipkart.com/fastrack-reflex-hello-1-69-hd-display-bt-calling-ai-voice-50-sport-smartwatch/p/itm10d0fbe1d80a6?pid=SMWGHEZRCTGYAT7Q&lid=LSTSMWGHEZRCTGYAT7QM0XHDU&marketplace=FLIPKART&q=fastrack+reflex+hello&store=ajy%2Fbuh&srno=s_1_1&otracker=AS_QueryStore_OrganicAutoSuggest_2_12_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_2_12_na_na_ps&fm=Search&iid=48d5adf2-9150-4b96-90e4-9df8b3c45807.SMWGHEZRCTGYAT7Q.SEARCH&ppt=sp&ppn=sp&ssid=xras4dvdfk0000001669952487009&qH=2a61451ad759ea51',
      },

      {
        comp_id: 'ss06',
        comp_name: 'realme',
        comp_model: 'realme Watch 3',
        comp_price: 3499,
        comp_prodDetails1:
          'Model Name                      realme watch 3  ',
        comp_prodDetails2: 'Display Size                    1.4inch',
        comp_prodDetails3: 'Display Resolution              360 x 360pixels',
        comp_prodDetails4: 'Call Function                   Yes',
        comp_prodDetails5: 'Bluetoth Version                5.0',
        comp_prodDetails6: 'Voice Control                   Yes',
        comp_prodDetails7: 'Operating System                N/A',
        comp_prodDetails8: 'Charge Type                     Wireless charger',
        comp_prodDetails9: 'Battery Life                    Upto 7 Days',
        comp_prodDetails10: 'Warranty Summary                1 Year',

        comp_img: '../../assets/project img/smart watch/r1.webp',
        comp_imgdetails1:'../../assets/project img/smart watch/r1.webp',
        comp_imgdetails2: '../../assets/project img/smart watch/r1.webp',
        comp_imgdetails3: '../../assets/project img/smart watch/r1.webp',

        comp_imgdetails: '../../assets/project img/watchdetails2/sam1.png',

        comp_link:
          'https://www.flipkart.com/samsung-watch-5-44mmsuper-amoled-displaylte-calling-body-composition-tracking/p/itmc9c74c7f4f22b?pid=SMWGH7W45SAFCCV4&lid=LSTSMWGH7W45SAFCCV46KCNIF&marketplace=FLIPKART&q=samsung+watch+5&store=ajy&srno=s_1_1&otracker=AS_Query_OrganicAutoSuggest_4_11_na_na_ps&otracker1=AS_Query_OrganicAutoSuggest_4_11_na_na_ps&fm=organic&iid=60c92518-9944-4ada-8c4e-7621232e9472.SMWGH7W45SAFCCV4.SEARCH&ppt=hp&ppn=homepage&ssid=wxhy5pxu740000001669951341793&qH=5da8e54149127e84',
      },

      {
        comp_id: 'ss07',
        comp_name: 'Noise',
        comp_model: 'Noise ColorFit Icon 2  ',
        comp_price: 2299,
        comp_prodDetails1:
        'Model Name                      Noise ColorFit Icon 2   ',
      comp_prodDetails2: 'Display Size                    1.4inch',
      comp_prodDetails3: 'Display Resolution              240 x 286pixels',
      comp_prodDetails4: 'Call Function                   Yes',
      comp_prodDetails5: 'Bluetoth Version                5.0',
      comp_prodDetails6: 'Voice Control                   Yes',
      comp_prodDetails7: 'Operating System                N/A',
      comp_prodDetails8: 'Charge Type                     Magnetic charger',
      comp_prodDetails9: 'Battery Life                    Upto 7 Days',
      comp_prodDetails10: 'Warranty Summary                1 Year',
        comp_prodDetails: 'abcd',
        comp_img: '../../assets/project img/smart watch/no1.webp',
        comp_imgdetails1: '../../assets/project img/smart watch/no1.webp',
        comp_imgdetails2: '../../assets/project img/smart watch/no2.webp',
        comp_imgdetails3: '../../assets/project img/smart watch/no3.webp',

        // comp_imgdetails: '../../assets/project img/watchdetails2/realme.png',
        comp_link:
          'https://www.flipkart.com/realme-watch-3-1-8-inch-horizon-curved-display-bluetooth-calling-smartwatch/p/itm23af2beb0e520?pid=SMWGFZBYEUSHWXNY&lid=LSTSMWGFZBYEUSHWXNYMRDJIO&marketplace=FLIPKART&q=realme+watch+3&store=ajy%2Fbuh&srno=s_1_1&otracker=search&otracker1=search&fm=search-autosuggest&iid=c1f4cfcb-4a16-409d-b739-ac992b20c0ab.SMWGFZBYEUSHWXNY.SEARCH&ppt=sp&ppn=sp&ssid=9y3sgk0ib40000001669952241524&qH=f76dfac9f7023e36',
      },
      {
        comp_id: 'ss08',
        comp_name: 'Noise',
        comp_model: 'Noise ColorFit Icon Buzz BT  ',
        comp_price: 1999,
        comp_prodDetails1: 'Diaplay Type                   Amoled',
        comp_prodDetails2: 'Display Size                    1.4inch',
        comp_prodDetails3: 'Display Resolution              240 x 286pixels',
        comp_prodDetails4: 'Call Function                   Yes',
        comp_prodDetails5: 'Bluetoth Version                5.0',
        comp_prodDetails6: 'Voice Control                   yes',
        comp_prodDetails7: 'Operating System                Wear Os',
        comp_prodDetails8: 'Charge Type                     Magnetic',
        comp_prodDetails9: 'Battery Life                    Upto 7days',
        comp_prodDetails10: 'Charge Time                    1.5 Hours',
        comp_prodDetails: 'abcd',
        comp_img: '../../assets/project img/smart watch/bz1.webp',
        comp_imgdetails1: '../../assets/project img/smart watch/bz1.webp',
        comp_imgdetails2: '../../assets/project img/smart watch/bz1.webp',
        comp_imgdetails3: '../../assets/project img/smart watch/bz1.webp',

        // comp_imgdetails: '../../assets/project img/watchdetails2/realme.png',
        comp_link:
          'https://www.flipkart.com/realme-watch-3-1-8-inch-horizon-curved-display-bluetooth-calling-smartwatch/p/itm23af2beb0e520?pid=SMWGFZBYEUSHWXNY&lid=LSTSMWGFZBYEUSHWXNYMRDJIO&marketplace=FLIPKART&q=realme+watch+3&store=ajy%2Fbuh&srno=s_1_1&otracker=search&otracker1=search&fm=search-autosuggest&iid=c1f4cfcb-4a16-409d-b739-ac992b20c0ab.SMWGFZBYEUSHWXNY.SEARCH&ppt=sp&ppn=sp&ssid=9y3sgk0ib40000001669952241524&qH=f76dfac9f7023e36',
      },
      {
        comp_id: 'ss09',
        comp_name: 'DIZO',
        comp_model: 'DIZO Watch 2 Sports ',
        comp_launchDate: '',
        comp_price: 1599,

        comp_prodDetails1:
        'Model Name                      DIZO Watch 2 Sports  ',
      comp_prodDetails2: 'Display Size                    1.4inch',
      comp_prodDetails3: 'Display Resolution              360 x 360pixels',
      comp_prodDetails4: 'Call Function                   Yes',
      comp_prodDetails5: 'Bluetoth Version                5.0',
      comp_prodDetails6: 'Voice Control                   Yes',
      comp_prodDetails7: 'Operating System                N/A',
      comp_prodDetails8: 'Charge Type                     Wireless charger',
      comp_prodDetails9: 'Battery Life                    Upto 7 Days',
      comp_prodDetails10: 'Warranty Summary                1 Year',

        comp_prodDetails: 'abcd',
        comp_img: '../../assets/project img/smart watch/dizo12.webp',
        comp_imgdetails1: '../../assets/project img/smart watch/dizo12.webp',
        comp_imgdetails2: '../../assets/project img/smart watch/dizo12.webp',
        comp_imgdetails3: '../../assets/project img/smart watch/dizo12.webp',
        // comp_imgdetails: '../../assets/project img/watchdetails2/dizo12.png',
        comp_link:
          'https://www.flipkart.com/dizo-watch-d-1-8-inch-dynamic-display-550nits-brightness-by-realme-techlife/p/itm327c18268a2a1?pid=SMWGEUCVA2XZY4JG&lid=LSTSMWGEUCVA2XZY4JGL9KJPA&marketplace=FLIPKART&q=dizzo+watch+d&store=ajy%2Fbuh&spotlightTagId=BestsellerId_ajy%2Fbuh&srno=s_1_2&otracker=search&otracker1=search&fm=Search&iid=b5112e82-f10f-46d4-97f7-2b2d157b8230.SMWGEUCVA2XZY4JG.SEARCH&ppt=sp&ppn=sp&ssid=7ab5pz74000000001669952302476&qH=f330bfc060e316dd',
      },
    ],
  },
  {
    prod_name: 'True wireless earbud',
    prod_id: 't01',
    prod_img: '../../assets/project img/banner img/tws.webp',
    prod_sub: [
      {
        comp_id: 'ts01',
        comp_name: 'apple',
        comp_model: 'APPLE Airpods Pro 2nd Gen',
        comp_launchDate: '',
        comp_price: 19990,
        comp_prodDetails1:
          'Designed For                          iOS Device,ipadOS Device',
        comp_prodDetails2: 'Bluetoth Version                      V5.0',
        comp_prodDetails3: 'battery Life                          5 hrs',
        comp_prodDetails4:
          'Headfone Type                         True Wireless',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             No',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10: 'Driver                                12mm',

        comp_img: '../../assets/project img/earpodes/apple.webp',
        comp_imgdetails1: '../../assets/project img/earpodes/apple.webp',
        comp_imgdetails2: '../../assets/project img/earpodes/ap1.webp',
        comp_imgdetails3: '../../assets/project img/earpodes/ap2.webp',

        comp_link:
          'https://www.flipkart.com/apple-airpods-pro-2nd-generation-bluetooth-headset/p/itmbfc083335b35c?pid=ACCGHWWGAAZDXNR2&lid=LSTACCGHWWGAAZDXNR2RMRPVQ&marketplace=FLIPKART&q=apple+earbuds+pro+2&store=0pm%2Ffcn&srno=s_1_1&otracker=AS_Query_OrganicAutoSuggest_2_13_na_na_ps&otracker1=AS_Query_OrganicAutoSuggest_2_13_na_na_ps&fm=search-autosuggest&iid=ca97afd3-72bc-461b-88a6-a40d164c4c1c.ACCGHWWGAAZDXNR2.SEARCH&ppt=sp&ppn=sp&ssid=eovb6g8exc0000001669952799574&qH=1e44045273648564',
      },
      {
        comp_id: 'ts02',
        comp_name: 'samsung',
        comp_model: 'SAMSUNG Galaxy Buds 2 PRO',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 17990,
        comp_prodDetails1:
          'Designed For                          Android Device',
        comp_prodDetails2: 'Bluetoth Version                      V5.3',
        comp_prodDetails3: 'battery Life                          7 hrs',
        comp_prodDetails4:
          'Headfone Type                         True Wireless',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10: 'Driver                                12mm',

        comp_img: '../../assets/project img/earpodes/sambudspro.jpg',
        comp_imgdetails1: '../../assets/project img/earpodes/sambudspro.jpg',
        comp_imgdetails2: '../../assets/project img/earpodes/s1.webp',
        comp_imgdetails3: '../../assets/project img/earpodes/s2.jpg',

        comp_link:
          'https://www.samsung.com/in/audio-sound/galaxy-buds/galaxy-buds2-pro-bora-purple-sm-r510nlvainu/?cid=in_pd_ppc_google_galaxy-buds2pro_none_samsunggalaxybuds2pro-eshop-bau-performancemax_20220815_18057530136-----1ur-501356l-2022',
      },
      {
        comp_id: 'ts03',
        comp_name: 'Google',
        comp_model: 'Google Pixel Buds A-Series',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 6999,
        comp_prodDetails1:
          'Designed For                          Android Device',
        comp_prodDetails2: 'Bluetoth Version                      V4',
        comp_prodDetails3: 'battery Life                          5 hrs',
        comp_prodDetails4:
          'Headfone Type                         True Wireless',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10: 'Driver                                12mm',

        comp_img: '../../assets/project img/earpodes/go1.webp',
        comp_imgdetails1: '../../assets/project img/earpodes/go1.webp',
        comp_imgdetails2: '../../assets/project img/earpodes/go2.webp',
        comp_imgdetails3: '../../assets/project img/earpodes/go3.webp',

        comp_link:
          'https://www.samsung.com/in/audio-sound/galaxy-buds/galaxy-buds2-pro-bora-purple-sm-r510nlvainu/?cid=in_pd_ppc_google_galaxy-buds2pro_none_samsunggalaxybuds2pro-eshop-bau-performancemax_20220815_18057530136-----1ur-501356l-2022',
      },
      {
        comp_id: 'ts04',
        comp_name: 'samsung',
        comp_model: 'SAMSUNG Galaxy Buds 2',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 6999,
        comp_prodDetails1:
          'Designed For                          Android Device',
        comp_prodDetails2: 'Bluetoth Version                      V5.2',
        comp_prodDetails3: 'battery Life                          5 hrs',
        comp_prodDetails4:
          'Headfone Type                         True Wireless',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10: 'Driver                                12mm',
        comp_img: '../../assets/project img/earpodes/samsung buds2.jpg',
        comp_imgdetails1: '../../assets/project img/earpodes/samsung buds2.jpg',
        comp_imgdetails2: '../../assets/project img/earpodes/sa2.webp',
        comp_imgdetails3: '../../assets/project img/earpodes/sa3.webp',

        comp_link:
          'https://www.flipkart.com/samsung-galaxy-buds-2-bluetooth-headset/p/itmc3c97a3bc62a8?pid=ACCG6885CVVD2HRS&lid=LSTACCG6885CVVD2HRSRGH8RF&marketplace=FLIPKART&q=galaxy+buds+2&store=0pm%2Ffcn%2F821%2Fa7x%2F2si&srno=s_1_1&otracker=AS_QueryStore_OrganicAutoSuggest_1_13_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_13_na_na_na&fm=search-autosuggest&iid=8fe742c0-0740-438a-a6ff-532785a2c58c.ACCG6885CVVD2HRS.SEARCH&ppt=sp&ppn=sp&ssid=ygcu2bw2nk0000001669953600871&qH=e0bf88967a8c8652',
      },
      {
        comp_id: 'ts05',
        comp_name: 'nothing',
        comp_model: 'OnePlus Buds Z2',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 4999,
        comp_prodDetails1:
          'Designed For                          Android Device',
        comp_prodDetails2: 'Bluetoth Version                      V5.2',
        comp_prodDetails3: 'battery Life                          5 hrs',
        comp_prodDetails4:
          'Headfone Type                         True Wireless',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10: 'Driver                                12mm',
        comp_img: '../../assets/project img/earpodes/2.png',
        comp_imgdetails1: '../../assets/project img/earpodes/2.png',
        comp_imgdetails: '../../assets/project img/twsdetails/sam.png',
        comp_link:
          'https://www.flipkart.com/oneplus-buds-z2-active-noise-cancellation-bluetooth-headset/p/itme6a38aecd5d70?pid=ACCGAECF8ZSUFE3A&lid=LSTACCGAECF8ZSUFE3AVEHLJV&marketplace=FLIPKART&q=one+plus+z2+earbuds&store=0pm%2Ffcn%2F821%2Fa7x%2F2si&srno=s_1_1&otracker=AS_QueryStore_OrganicAutoSuggest_1_12_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_12_na_na_ps&fm=search-autosuggest&iid=c833c1f6-d3eb-4099-adbd-137603c710ed.ACCGAECF8ZSUFE3A.SEARCH&ppt=sp&ppn=sp&ssid=su1oie5lwg0000001669954438815&qH=805d094dee8c3fd8',
      },
      {
        comp_id: 'ts06',
        comp_name: 'Realme',
        comp_model: 'realme Buds Air 3',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 3999,
        comp_prodDetails1:
          'Designed For                          Android Device',
        comp_prodDetails2: 'Bluetoth Version                      V5.2',
        comp_prodDetails3: 'battery Life                          8 hrs',
        comp_prodDetails4:
          'Headfone Type                         True Wireless',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10: 'Driver                                12mm',
        comp_img: '../../assets/project img/earpodes/realme.jpg',
        comp_imgdetails1: '../../assets/project img/earpodes/realme.jpg',
        comp_imgdetails2: '../../assets/project img/earpodes/realme.jpg',
        comp_imgdetails3: '../../assets/project img/earpodes/realme.jpg',

        comp_link:
          'https://www.flipkart.com/realme-buds-air-3-neo-up-30-hours-playback-fast-charge-bluetooth-headset/p/itmd5fa6d8758897?pid=ACCGFW9XEDWXEGGZ&lid=LSTACCGFW9XEDWXEGGZ8HHHQ5&marketplace=FLIPKART&q=realme+buds+air+3&store=0pm%2Ffcn%2F821%2Fa7x%2F2si&spotlightTagId=BestsellerId_0pm%2Ffcn%2F821%2Fa7x%2F2si&srno=s_1_1&otracker=AS_QueryStore_OrganicAutoSuggest_1_15_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_15_na_na_ps&fm=search-autosuggest&iid=214eb149-cafb-4e16-b10c-dc841c6d7432.ACCGFW9XEDWXEGGZ.SEARCH&ppt=sp&ppn=sp&ssid=4xsgakckzk0000001669953781673&qH=2f03e3297acfee30',
      },

      {
        comp_id: 'ts07',
        comp_name: 'oppo',
        comp_model: 'OPPO Enco Buds 2',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 1999,
        comp_prodDetails1:
          'Designed For                          Android Device',
        comp_prodDetails2: 'Bluetoth Version                      V5.3',
        comp_prodDetails3: 'battery Life                          5 hrs',
        comp_prodDetails4:
          'Headfone Type                         True Wireless',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10: 'Driver                                10mm',
        comp_img: '../../assets/project img/earpodes/oppo.webp',
        comp_imgdetails1: '../../assets/project img/earpodes/oppo.webp',
        comp_imgdetails2: '../../assets/project img/earpodes/oppo.webp',
        comp_imgdetails3: '../../assets/project img/earpodes/oppo.webp',

        comp_link:
          'https://www.flipkart.com/oppo-enco-buds-2-28-hours-battery-life-deep-noise-cancellation-bluetooth-headset/p/itm3344fa26518ed?pid=ACCGH7YZY6AHGCHJ&lid=LSTACCGH7YZY6AHGCHJHLWF41&marketplace=FLIPKART&q=oppo+enco+buds+2&store=0pm%2Ffcn%2F821%2Fa7x%2F2si&spotlightTagId=BestsellerId_0pm%2Ffcn%2F821%2Fa7x%2F2si&srno=s_1_3&otracker=AS_QueryStore_OrganicAutoSuggest_2_4_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_2_4_na_na_ps&fm=search-autosuggest&iid=cfed900e-ea97-4bf5-99ad-10e3f0a0c540.ACCGH7YZY6AHGCHJ.SEARCH&ppt=sp&ppn=sp&ssid=b038gaqlkw0000001669953880051&qH=3619b875e57c6769',
      },
      {
        comp_id: 'ts08',
        comp_name: 'oppo',
        comp_model: 'realme Techlife Buds T100 ',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 1690,
        comp_prodDetails1:
          'Designed For                          Android Device',
        comp_prodDetails2: 'Bluetoth Version                      V5.3',
        comp_prodDetails3: 'battery Life                          5 hrs',
        comp_prodDetails4:
          'Headfone Type                         True Wireless',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10: 'Driver                                10mm',
        comp_img: '../../assets/project img/earpodes/rt1.webp',
        comp_imgdetails1: '../../assets/project img/earpodes/rt1.webp',
        comp_imgdetails2: '../../assets/project img/earpodes/rt2.webp',
        comp_imgdetails3: '../../assets/project img/earpodes/rt3.webp',

        comp_link:
          'https://www.flipkart.com/oppo-enco-buds-2-28-hours-battery-life-deep-noise-cancellation-bluetooth-headset/p/itm3344fa26518ed?pid=ACCGH7YZY6AHGCHJ&lid=LSTACCGH7YZY6AHGCHJHLWF41&marketplace=FLIPKART&q=oppo+enco+buds+2&store=0pm%2Ffcn%2F821%2Fa7x%2F2si&spotlightTagId=BestsellerId_0pm%2Ffcn%2F821%2Fa7x%2F2si&srno=s_1_3&otracker=AS_QueryStore_OrganicAutoSuggest_2_4_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_2_4_na_na_ps&fm=search-autosuggest&iid=cfed900e-ea97-4bf5-99ad-10e3f0a0c540.ACCGH7YZY6AHGCHJ.SEARCH&ppt=sp&ppn=sp&ssid=b038gaqlkw0000001669953880051&qH=3619b875e57c6769',
      },
      {
        comp_id: 'ts09',
        comp_name: 'oppo',
        comp_model: 'boAt Airdopes 161',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 1399,
        comp_prodDetails1:
          'Designed For                          Android Device',
        comp_prodDetails2: 'Bluetoth Version                      V5.0',
        comp_prodDetails3: 'battery Life                          7 hrs',
        comp_prodDetails4:
          'Headfone Type                         True Wireless',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10: 'Driver                                10mm',
        comp_img: '../../assets/project img/earpodes/b1.webp',
        comp_imgdetails1: '../../assets/project img/earpodes/b1.webp',
        comp_imgdetails2: '../../assets/project img/earpodes/b2.webp',
        comp_imgdetails3: '../../assets/project img/earpodes/b3.webp',

        comp_link:
          'https://www.flipkart.com/oppo-enco-buds-2-28-hours-battery-life-deep-noise-cancellation-bluetooth-headset/p/itm3344fa26518ed?pid=ACCGH7YZY6AHGCHJ&lid=LSTACCGH7YZY6AHGCHJHLWF41&marketplace=FLIPKART&q=oppo+enco+buds+2&store=0pm%2Ffcn%2F821%2Fa7x%2F2si&spotlightTagId=BestsellerId_0pm%2Ffcn%2F821%2Fa7x%2F2si&srno=s_1_3&otracker=AS_QueryStore_OrganicAutoSuggest_2_4_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_2_4_na_na_ps&fm=search-autosuggest&iid=cfed900e-ea97-4bf5-99ad-10e3f0a0c540.ACCGH7YZY6AHGCHJ.SEARCH&ppt=sp&ppn=sp&ssid=b038gaqlkw0000001669953880051&qH=3619b875e57c6769',
      },
    ],
  },
  {
    prod_name: 'neckbands',
    prod_id: 'n01',
    prod_img: '../../assets/project img/banner img/Z2.webp',
    prod_sub: [
      {
        comp_id: 'ns01',
        comp_name: 'realme',
        comp_model: 'realme Buds Wireless 2',
        comp_launchDate: '',
        comp_price: 2299,
        comp_prodDetails1:
          'Model Name                            Buds Wireless 2',
        comp_prodDetails2: 'Bluetoth Version                      V5.2',
        comp_prodDetails3: 'battery Life                          22 hrs',
        comp_prodDetails4: 'Headfone Type                         In the Ear',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10:
          'Driver Type                           Bass Boost Plus(13.6mm)',
        comp_prodDetails: 'abcd',
        comp_img: '../../assets/project img/oneplus neckbands/realme.jpeg',
        comp_imgdetails1:
          '../../assets/project img/oneplus neckbands/realme.jpeg',
        comp_imgdetails2: '../../assets/project img/oneplus neckbands/re1.webp',
        comp_imgdetails3: '../../assets/project img/oneplus neckbands/re2.webp',
        comp_link:
          'https://www.flipkart.com/realme-buds-wireless-2-dart-charge-active-noise-cancellation-anc-bluetooth-headset/p/itme567acdbe4ccb?pid=ACCGGZDU2J9XE22G&lid=LSTACCGGZDU2J9XE22GQ1VA0H&marketplace=FLIPKART&q=realme+buds+wireless+2&store=0pm%2Ffcn&srno=s_1_1&otracker=AS_Query_OrganicAutoSuggest_4_12_na_na_ps&otracker1=AS_Query_OrganicAutoSuggest_4_12_na_na_ps&fm=search-autosuggest&iid=bd0738a4-40e8-4806-986d-389d81a4975c.ACCGGZDU2J9XE22G.SEARCH&ppt=sp&ppn=sp&ssid=qqujq74bb40000001669955899371&qH=1ff99ee264821f7a',
      },
      {
        comp_id: 'ns02',
        comp_name: 'oneplus',
        comp_model: 'OnePlus Bullets Wireless Z2',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 1999,
        comp_prodDetails1:
          'Model Name                            OnePlus Bullets Wireless Z2',
        comp_prodDetails2: 'Bluetoth Version                      V5.0',
        comp_prodDetails3: 'battery Life                          22 hrs',
        comp_prodDetails4: 'Headfone Type                         In the Ear',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              No',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10:
          'Driver Type                           Bass Boost (12mm)',
        comp_img: '../../assets/project img/oneplus neckbands/oneplus3.webp',
        comp_imgdetails1:
          '../../assets/project img/oneplus neckbands/oneplus3.webp',
        comp_imgdetails2:
          '../../assets/project img/oneplus neckbands/one2.webp',
        comp_imgdetails3:
          '../../assets/project img/oneplus neckbands/one3.webp',

        comp_link:
          'https://www.flipkart.com/oneplus-bullets-wireless-z2-fast-charge-30-hrs-battery-life-earphones-mic-bluetooth-headset/p/itm1b9cd98911a2a?pid=ACCGC4GN5SQR7ZCZ&lid=LSTACCGC4GN5SQR7ZCZJIQWGQ&marketplace=FLIPKART&q=oneplus+wireless+z2&store=search.flipkart.com&spotlightTagId=BestsellerId_search.flipkart.com&srno=s_1_1&otracker=search&otracker1=search&fm=Search&iid=81a446f1-5861-44f2-b7a2-7c73d404f23f.ACCGC4GN5SQR7ZCZ.SEARCH&ppt=sp&ppn=sp&ssid=eywrtbylmo0000001669955574341&qH=44a12e1a44a0478c',
      },
      {
        comp_id: 'ns03',
        comp_name: 'oppo',
        comp_model: 'OPPO Enco M32',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 1799,
        comp_prodDetails1:
          'Model Name                            OPPO Enco M32',
        comp_prodDetails2: 'Bluetoth Version                      V5.2',
        comp_prodDetails3: 'battery Life                          22 hrs',
        comp_prodDetails4: 'Headfone Type                         In the Ear',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10:
          'Driver Type                           Bass Boost Plus(13.6mm)',
        comp_img: '../../assets/project img/oneplus neckbands/oppo.jpg',
        comp_imgdetails1: '../../assets/project img/oneplus neckbands/oppo.jpg',
        comp_imgdetails: '../../assets/project img/nedetails/oppo.png',
        comp_link:
          'https://www.flipkart.com/oppo-enco-m32-bluetooth-headset/p/itm6c8f7a059df37?pid=ACCGARV72QDWAGG6&lid=LSTACCGARV72QDWAGG6BQGCEM&marketplace=FLIPKART&q=oppo+enco+m32&store=0pm%2Ffcn%2F821%2Fa7x%2F2rv&srno=s_1_1&otracker=AS_QueryStore_OrganicAutoSuggest_3_8_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_3_8_na_na_ps&fm=search-autosuggest&iid=14ab524d-8766-4043-a7ee-be35b912c34b.ACCGARV72QDWAGG6.SEARCH&ppt=sp&ppn=sp&ssid=fn4hn4oclc0000001669955764700&qH=cfae0427490422d5',
      },
      {
        comp_id: 'ns04',
        comp_name: 'realme',
        comp_model: 'realme Buds Wireless 2S ',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 1499,
        comp_prodDetails1:
          'Model Name                            realme Buds Wireless 2S',
        comp_prodDetails2: 'Bluetoth Version                      V5.2',
        comp_prodDetails3: 'battery Life                          22 hrs',
        comp_prodDetails4: 'Headfone Type                         In the Ear',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10:
          'Driver Type                           Bass Boost Plus(13.6mm)',
        comp_img: '../../assets/project img/oneplus neckbands/s2.webp',
        comp_imgdetails1: '../../assets/project img/oneplus neckbands/s2.webp',
        comp_imgdetails2: '../../assets/project img/oneplus neckbands/s2.webp',
        comp_imgdetails3: '../../assets/project img/oneplus neckbands/s2.webp',
        comp_imgdetails: '../../assets/project img/nedetails/oppo.png',
        comp_link:
          'https://www.flipkart.com/oppo-enco-m32-bluetooth-headset/p/itm6c8f7a059df37?pid=ACCGARV72QDWAGG6&lid=LSTACCGARV72QDWAGG6BQGCEM&marketplace=FLIPKART&q=oppo+enco+m32&store=0pm%2Ffcn%2F821%2Fa7x%2F2rv&srno=s_1_1&otracker=AS_QueryStore_OrganicAutoSuggest_3_8_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_3_8_na_na_ps&fm=search-autosuggest&iid=14ab524d-8766-4043-a7ee-be35b912c34b.ACCGARV72QDWAGG6.SEARCH&ppt=sp&ppn=sp&ssid=fn4hn4oclc0000001669955764700&qH=cfae0427490422d5',
      },
      {
        comp_id: 'ns05',
        comp_name: 'realme',
        comp_model: 'realme Buds Wireless 2 Neo ',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 1299,
        comp_prodDetails1:
          'Model Name                            Buds Wireless 2 Neo',
        comp_prodDetails2: 'Bluetoth Version                      V5.0',
        comp_prodDetails3: 'battery Life                          17 hrs',
        comp_prodDetails4: 'Headfone Type                         In the Ear',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           No',
        comp_prodDetails7: 'Deep Bass                             No',
        comp_prodDetails8: 'ANC Mode                              No',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10:
          'Driver Type                           Bass Boost (11.2mm)',
        comp_img: '../../assets/project img/oneplus neckbands/neo1.webp',
        comp_imgdetails1:
          '../../assets/project img/oneplus neckbands/neo1.webp',
        comp_imgdetails2:
          '../../assets/project img/oneplus neckbands/neo2.webp',
        comp_imgdetails3:
          '../../assets/project img/oneplus neckbands/neo3.webp',
        comp_imgdetails: '../../assets/project img/nedetails/oppo.png',

        comp_link:
          'https://www.flipkart.com/oppo-enco-m32-bluetooth-headset/p/itm6c8f7a059df37?pid=ACCGARV72QDWAGG6&lid=LSTACCGARV72QDWAGG6BQGCEM&marketplace=FLIPKART&q=oppo+enco+m32&store=0pm%2Ffcn%2F821%2Fa7x%2F2rv&srno=s_1_1&otracker=AS_QueryStore_OrganicAutoSuggest_3_8_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_3_8_na_na_ps&fm=search-autosuggest&iid=14ab524d-8766-4043-a7ee-be35b912c34b.ACCGARV72QDWAGG6.SEARCH&ppt=sp&ppn=sp&ssid=fn4hn4oclc0000001669955764700&qH=cfae0427490422d5',
      },
      {
        comp_id: 'ns06',
        comp_name: 'DIZO',
        comp_model: 'DIZO Wireless Dash',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 1299,
        comp_prodDetails1:
          'Model Name                            DIZO Wireless Dash',
        comp_prodDetails2: 'Bluetoth Version                      V5.2',
        comp_prodDetails3: 'battery Life                          22 hrs',
        comp_prodDetails4: 'Headfone Type                         In the Ear',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           yes',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              Yes',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10: 'Driver Type                           (10mm)',
        comp_img: '../../assets/project img/oneplus neckbands/dizo1.webp',
        comp_imgdetails1:
          '../../assets/project img/oneplus neckbands/dizo1.webp',
        comp_imgdetails2:
          '../../assets/project img/oneplus neckbands/dizo1.webp',
        comp_imgdetails3:
          '../../assets/project img/oneplus neckbands/dizo1.webp',
        comp_imgdetails: '../../assets/project img/nedetails/oppo.png',
        comp_link:
          'https://www.flipkart.com/oppo-enco-m32-bluetooth-headset/p/itm6c8f7a059df37?pid=ACCGARV72QDWAGG6&lid=LSTACCGARV72QDWAGG6BQGCEM&marketplace=FLIPKART&q=oppo+enco+m32&store=0pm%2Ffcn%2F821%2Fa7x%2F2rv&srno=s_1_1&otracker=AS_QueryStore_OrganicAutoSuggest_3_8_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_3_8_na_na_ps&fm=search-autosuggest&iid=14ab524d-8766-4043-a7ee-be35b912c34b.ACCGARV72QDWAGG6.SEARCH&ppt=sp&ppn=sp&ssid=fn4hn4oclc0000001669955764700&qH=cfae0427490422d5',
      },
      {
        comp_id: 'ns07',
        comp_name: 'boat',
        comp_model: 'boAt Rockerz 235 Pro',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 1299,
        comp_prodDetails1:
          'Model Name                            boAt Rockerz 235 Pro',
        comp_prodDetails2: 'Bluetoth Version                      V5.2',
        comp_prodDetails3: 'battery Life                          27 hrs',
        comp_prodDetails4: 'Headfone Type                         In the Ear',
        comp_prodDetails5: 'Water Resistance                      yes',
        comp_prodDetails6: 'Sweat Proof                           No',
        comp_prodDetails7: 'Deep Bass                             Yes',
        comp_prodDetails8: 'ANC Mode                              No',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10:
          'Driver Type                           Bass Boost (12mm)',
        comp_img: '../../assets/project img/oneplus neckbands/boat2.webp',
        comp_imgdetails1:
          '../../assets/project img/oneplus neckbands/boat2.webp',
        comp_imgdetails2: '../../assets/project img/oneplus neckbands/bo2.webp',
        comp_imgdetails3: '../../assets/project img/oneplus neckbands/bo2.webp',
        comp_imgdetails: '../../assets/project img/nedetails/boat.png',
        comp_link:
          'https://www.flipkart.com/boat-rockerz-235-pro-upto-20-hours-playback-asap-charge-bluetooth-headset/p/itm27ea35acb2cb6?pid=ACCGBVMGY9SPY7KZ&lid=LSTACCGBVMGY9SPY7KZHQEPR9&marketplace=FLIPKART&q=boat+bluetooth+headphones&store=0pm%2Ffcn%2F821%2Fa7x%2F2rv&srno=s_1_8&otracker=AS_QueryStore_OrganicAutoSuggest_1_5_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_5_na_na_ps&fm=search-autosuggest&iid=cbfb69ac-afd4-4870-8f98-d8a337df43a6.ACCGBVMGY9SPY7KZ.SEARCH&ppt=sp&ppn=sp&ssid=vwdhd2klm80000001669956133396&qH=8ffd5ae5b337d901',
      },
      {
        comp_id: 'ns08',
        comp_name: 'DIZO',
        comp_model: 'DIZO Wireless Active',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 1099,
        comp_prodDetails1:
          'Model Name                            DIZO Wireless Active',
        comp_prodDetails2: 'Bluetoth Version                      V5.0',
        comp_prodDetails3: 'battery Life                          23 hrs',
        comp_prodDetails4: 'Headfone Type                         In the Ear',
        comp_prodDetails5: 'Water Resistance                      No',
        comp_prodDetails6: 'Sweat Proof                           No',
        comp_prodDetails7: 'Deep Bass                             No',
        comp_prodDetails8: 'ANC Mode                              No',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10: 'Driver Type                           (10mm)',
        comp_img: '../../assets/project img/oneplus neckbands/di1.webp',
        comp_imgdetails1: '../../assets/project img/oneplus neckbands/di1.webp',
        comp_imgdetails2: '../../assets/project img/oneplus neckbands/di1.webp',
        comp_imgdetails3: '../../assets/project img/oneplus neckbands/di1.webp',
        comp_imgdetails: '../../assets/project img/nedetails/oppo.png',
        comp_link:
          'https://www.flipkart.com/oppo-enco-m32-bluetooth-headset/p/itm6c8f7a059df37?pid=ACCGARV72QDWAGG6&lid=LSTACCGARV72QDWAGG6BQGCEM&marketplace=FLIPKART&q=oppo+enco+m32&store=0pm%2Ffcn%2F821%2Fa7x%2F2rv&srno=s_1_1&otracker=AS_QueryStore_OrganicAutoSuggest_3_8_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_3_8_na_na_ps&fm=search-autosuggest&iid=14ab524d-8766-4043-a7ee-be35b912c34b.ACCGARV72QDWAGG6.SEARCH&ppt=sp&ppn=sp&ssid=fn4hn4oclc0000001669955764700&qH=cfae0427490422d5',
      },
      {
        comp_id: 'ns09',
        comp_name: 'PTron',
        comp_model: 'PTron InTunes Beats ',
        comp_launchDate: '',
        comp_prodDetails: 'abcd',
        comp_price: 849,
        comp_prodDetails1:
          'Model Name                            Buds Wireless 2',
        comp_prodDetails2: 'Bluetoth Version                      V5.2',
        comp_prodDetails3: 'battery Life                          4 hrs',
        comp_prodDetails4: 'Headfone Type                         In the Ear',
        comp_prodDetails5: 'Water Resistance                      No',
        comp_prodDetails6: 'Sweat Proof                           Yes',
        comp_prodDetails7: 'Deep Bass                             No',
        comp_prodDetails8: 'ANC Mode                              No',
        comp_prodDetails9: 'Warranty Summary                      1 Year',
        comp_prodDetails10:
          'Driver Type                           Dynamic(10mm)',
        comp_img: '../../assets/project img/oneplus neckbands/pt.webp',
        comp_imgdetails1: '../../assets/project img/oneplus neckbands/pt.webp',
        comp_imgdetails2: '../../assets/project img/oneplus neckbands/pt2.webp',
        comp_imgdetails3: '../../assets/project img/oneplus neckbands/pt3.webp',
        comp_imgdetails: '../../assets/project img/nedetails/boat.png',
        comp_link:
          'https://www.flipkart.com/boat-rockerz-235-pro-upto-20-hours-playback-asap-charge-bluetooth-headset/p/itm27ea35acb2cb6?pid=ACCGBVMGY9SPY7KZ&lid=LSTACCGBVMGY9SPY7KZHQEPR9&marketplace=FLIPKART&q=boat+bluetooth+headphones&store=0pm%2Ffcn%2F821%2Fa7x%2F2rv&srno=s_1_8&otracker=AS_QueryStore_OrganicAutoSuggest_1_5_na_na_ps&otracker1=AS_QueryStore_OrganicAutoSuggest_1_5_na_na_ps&fm=search-autosuggest&iid=cbfb69ac-afd4-4870-8f98-d8a337df43a6.ACCGBVMGY9SPY7KZ.SEARCH&ppt=sp&ppn=sp&ssid=vwdhd2klm80000001669956133396&qH=8ffd5ae5b337d901',
      },
    ],
  },
];
